import Head from 'next/head';
import { useState } from 'react';
import { useQuery } from 'urql';
import Product from '../components/Product';
import { PRODUCT_QUERY } from '../lib/query';
import { Gallery } from '../styles/Gallery';

export default function Home() {
  // FETCH products from strpi
  const [results] = useQuery({query: PRODUCT_QUERY});
  const { data, fetching, error } = results;

  // Check for the data coming in
  if(fetching) return <p>Loading...</p>
  if(error) return <p>Oh no... {error.message}</p>
  const products = data.products.data;
  console.log(products);
  return (
    <div>
      <Head>
        <title>Styled HomePage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Gallery>
          {products.map((product)=><Product product={product} key={product.attributes.slug}/>)}
        </Gallery>
      </main>
    </div>
  )
}
